### ISSUE TITLE
[Security issue] Update octokit dependency 

### ISSUE THREAD

**Issue by techware01** [tweaselORG/autopy#9]
According to npm audit autopy depends on a vulnarable version of octokit: 

octokit  <3.1.2
Severity: high
Unauthenticated Denial of Service in the octokit/webhooks library - https://github.com/advisories/GHSA-pwfr-8pq7-x9qv

"It is recommend that all users upgrade to the latest version of [octokit/webhooks.js](https://github.com/octokit/webhooks.js) or use one of the updated back ported versions."

**Comment by baltpeter** [comment]
Thanks for the report! However, I'm pretty sure that we are not affected by this issue. From reading the advisory and looking and looking at the [fix](https://github.com/octokit/webhooks.js/commit/26184386d4a1022ea923c28b8869cf397da07b85), the vuln only affects applications that handle webhooks received from GitHub and even then, the issue is and unhandled error that could cause a crash.

We're only using Octokit to fetch releases using the API:

https://github.com/tweaselORG/autopy/blob/200a343cfcdbcc7ee1b01c5d20ceea2212c0bc3b/src/index.ts#L46-L55

That being said, I have now enabled Dependabot on this repository and we'll merge the PRs when we publish the next release.

**Comment by techware01** [comment]
Thanks's for looking into this and the clarification :)
